services:
  baota:
    image: pomerium/pomerium:v0.14.2
    ports:
      - 8888:8888
      - 80:80
  desktop:
    image: codercom/code-server:3.10.1
    ports:
      - 8080:80
    volumes:
      - ./code-server:/home/coder/project
    command: --auth none --disable-telemetry /home/coder/project
